### ISSUE TITLE
Error executing process > 'SCOV2_TREE:FILTERS_GISIAD:GISIAD_FILTERS:FILTERS_GISIAD (1)'

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#5]
# Error message

```
Error executing process > 'SCOV2_TREE:FILTERS_GISIAD:GISIAD_FILTERS:FILTERS_GISIAD (1)'

Caused by:
  Process `SCOV2_TREE:FILTERS_GISIAD:GISIAD_FILTERS:FILTERS_GISIAD (1)` terminated with an error exit status (1)

Command executed:

  filter_gisaid_sequences.py -i sequences_fasta_2021_05_16.tar.xz -m metadata_tsv_2021_05_16.tar.xz \
                             -s '' -R lineages_report.csv -r '' -c '' \
                             -of filtered_gisiad_sequences.fasta -om1 metadata_1.tsv -om2 metadata_2.tsv \
                             -lmin 10000 -lmax 32000 -x 3000 -ot stat.tsv
```

---

# Python stacktrace

```
  /usr/local/lib/python3.9/site-packages/click/core.py:1062: DtypeWarning: Columns (13,16) have mixed types.Specify dtype option on import or set low_memory=False.
    rv = self.invoke(ctx)
  Traceback (most recent call last):
    File "/home/pkruczkiewicz/.nextflow/assets/nhhaidee/scovtree/bin/filter_gisaid_sequences.py", line 189, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
      return __callback(*args, **kwargs)
    File "/home/pkruczkiewicz/.nextflow/assets/nhhaidee/scovtree/bin/filter_gisaid_sequences.py", line 130, in main
      for strains, seq in SimpleFastaParser(fin):
    File "/usr/local/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 47, in SimpleFastaParser
      for line in handle:
    File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
      (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

---

# Solution

The GISAID tar.xz FASTA sequences cannot be parsed using BioPython's SimpleFastaParser since reading from a file using the tarfile module returns byte string that need to be decoded. Please see the following code that you could use instead:

```python
def read_fasta(handle) -> Iterator[Tuple[str, str]]:
    # Skip any text before the first record (e.g. blank lines, comments)
    for line in handle:
        line = line.decode()
        if line[0] == ">":
            title = line[1:].rstrip()
            break
    else:
        # no break encountered - probably an empty file
        return
    lines = []
    for line in handle:
        line = line.decode()
        if line[0] == ">":
            yield title, "".join(lines).replace(" ", "").replace("\r", "")
            lines = []
            title = line[1:].rstrip()
            continue
        lines.append(line.rstrip())

    yield title, "".join(lines).replace(" ", "").replace("\r", "")
```

**Comment by nhhaidee** [comment]
@peterk87 Fixed by https://github.com/nhhaidee/scovtree/pull/9
